### PR TITLE
powered door & onTab commands

### PR DESCRIPTION
**Pull request by ikbenignace**

### CODE REVIEW

**Comment by TheTurkeyDev** [comment]
I didn't remember seeing this PR come across. Was this done?

**Comment by ikbenignace** [comment]
It was ready actually, but there was a bug with some signs, I do recommend when all my PR are merged, to test it out and fix the minor bugs. Didn't knew what caused it yet. Long time ago

**Comment by CHollasch** [comment]
Hi friends

**Comment by TheTurkeyDev** [comment]
> Hi friends

Why hello

**Pull request merged**
