### PR TITLE
fixed it not removing spawnpoint blocks

### PR DESCRIPTION
**Pull request by InsideIntel**

### CODE REVIEW

**Review by TheTurkeyDev — COMMENTED** [review]
If you removed game. Where is it coming from now for game.spawnManager?

**Comment by InsideIntel** [comment]
it's coming from BaseAction of course

**Comment by TheTurkeyDev** [comment]
Ah... yeah you'd be right. I still want to look into this myself. This does make things work, but it doesn't fix the issue so I might not merge this in. We'll see

**Comment by InsideIntel** [comment]
idm

**Pull request closed without merging**
